language: node_js
node_js:
- 14.15.1
after_success:
- chmod +x .travis/push.sh
- ".travis/push.sh"
env:
  global:
    secure: mb3ZCjk9FJqLuhel55egPrPw+CBv+1kP5kaRBliJJ17lx+uU8+43ABsoMxZzetqTQR4c2pNsxbkCyFvzrVMZ2hZzS02RBkqAs10vA87YeEz1zfEvE0xVBG1Nz30D5A0mTNQUJrcp0qxgHFh7krfROYU/lOA6Ib87jRrMEO6b2NHiNZ8lQYG2Iut8CbNk6XNC4sd+DfmbArO0gV5co3JuMzCXDVUnlNLpFLMOQ2lKc9hclrf2JGmcpUhmUzTMlNW4PcTB1vLXR9Am9U+DRgHjVj8uK+4hdjrKcTgZZTZshZ6fIwpZ1vvIcz6Vioc1IBrWxI4qhGFyoWJaBRkY5/T8wZHVG/Vb0dpv0tyePtUpGWybplEgQXFUQ3VPsCf38+L5ohBZJKl3wdHKBJVULoUD5YY9/uOY3vKp3Y+fk3wMrfDcyvAvOvl4nK6xIcZVTXIOTzH3qeBZfWH7bqBci97uIPQ3bEmKNiBEJyCCFrogDcGMmiIcdDGn67XNDWT1pBloPBpi/zpJSHBmXSK686rxHW5IO9hZgdF50u+YSUEMCCb0IOfutTK5EKk71LiYUq17xQNInwSIjwH/OHa3oaHywSNXvEb77hKLGrJ6wtFgJHLP6iiOUTcb2hmx3qjsbi135DzUkZ2eGQTVHQgmGPYjfTwVZaJuPm8rYwwobIJy0f4=
